In [35]:
import numpy as np
from tqdm import tqdm
from sklearn.linear_model import Perceptron
import copy
import math
import cvxpy as cp

In [36]:
class Gentile():
    def __init__(self, p, alpha, B, C):
        self.alpha = alpha
        self.B = B
        self.C = C
        self.p = p
        self.q = self.p/(self.p - 1)
        
    def solve(self, X, y):
        dim = X.shape[1]
        self.initialize(dim)
        for _ in range(1000):
            self.forward(X, y)
            accuracy_metric = np.sum(y * (X @ self.weights) > 0)/X.shape[0]
            print("Accuracy: {}%".format(accuracy_metric))
        return self.weights
    
    def initialize(self, dim):
        self.weights = np.zeros(dim)
        self.k = 1
        
    def forward(self, X, y):
        self.gamma = self.B * np.sqrt(self.p - 1) * 1/np.sqrt(self.k)
    
        
        for t in range(X.shape[0]):
            if y[t] * np.dot(self.weights,X[t]) <= (1 - self.alpha) * self.gamma:
                self.eta = self.C/np.sqrt(self.p - 1) * 1/np.sqrt(self.k)
                w_prime = self.finv(self.f(self.weights)+ self.eta * y[t] * X[t])
                q_norm = np.linalg.norm(w_prime, ord=self.q)
                self.weights = w_prime/max(1, q_norm)
                self.k += 1
            
                
    def f(self, w):
        numerator = np.sign(w) * np.power(abs(w), self.q - 1)
        denominator = np.power(np.linalg.norm(w, ord=self.q), self.q - 2)
        return numerator/denominator
    
    def finv(self, theta):
        numerator = np.sign(theta) * np.power(abs(theta), self.p - 1)
        denominator = np.power(np.linalg.norm(theta, ord=self.p), self.p - 2)
        return numerator/denominator
        
    

In [48]:
def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0) # only difference

class Pnorm_accelerated():
    def __init__(self, p):

        self.p = p
        self.q = p/(p-1)
        self.eta_w = 1/(2 * self.q - 2)
    
    def initialize(self, X, y):
        self.ws = np.array([])
        self.probs = np.array([])
        self.probs = np.append(self.probs, np.asarray([1] * X.shape[0])/X.shape[0])
        self.probs = self.probs.reshape(1, X.shape[0])
        
    
    def iterate(self, X, y):
        self.initialize(X, y)
        M = X * y[:, np.newaxis]
        percent_accuracy = 0
        for t in tqdm(range(1000), desc="Acc: {0:.3g}".format(percent_accuracy)):
            w = cp.Variable(len(X[0]))
            banana = -1 * np.sum(self.probs @ M, axis=0) @ w + -1 * self.probs[-1] @ M @ w + self.eta_w/2 * cp.square(cp.atoms.pnorm(w))
            problem = cp.Problem(cp.Minimize(banana) )
            try:
                problem.solve()
            except:
                problem.solve(solver="SCS")
            self.w = w.value
            
            if len(self.ws) == 0:
                self.ws = np.asarray(self.w).reshape(1, X.shape[0])
            else:
                self.ws = np.vstack([self.ws, self.w.reshape(1, X.shape[0])])
            
            prob_weightings = -1/2 * np.sum(M @ self.ws.T, axis=1) - 1
            prob_weightings = prob_weightings/abs(np.sum(prob_weightings))
            self.prob = softmax(prob_weightings)
            self.probs = np.vstack([self.probs, self.prob.reshape(1, X.shape[0])])
            if np.isnan(self.probs).any():
                breakpoint()  
            print(percent_accuracy)
            percent_accuracy = np.sum(M @ np.mean(pna.ws, axis=0).T > 0)/M.shape[0]
            if((M @ np.mean(pna.ws, axis=0).T > 0).all()):
                break
                
        return np.mean(pna.ws, axis=0)

In [49]:
def get_dataset(dim):
    X = []
    y = []
    for i in range(dim):
        if len(X) == 0:
            vec = [0] * dim
            vec[0] = 1
            X.append(np.asarray(vec))
        else:
            vec = math.pow(-1, i) * abs(copy.deepcopy(X[i-1]))
            vec[i] = math.pow(-1, i+1)
            X.append(np.asarray(vec))
        y.append(math.pow(-1, i+1))
    return np.asarray(X), np.asarray(y)

In [50]:
n = 10
points = np.zeros((n,n))
labels = np.zeros(n)
for i in range(n):
    points[i,:i] = (-1)**(i+1)
    points[i,i] = (-1)**i
#     points[i,:] = points[i]/np.linalg.norm(points[i])
    labels[i] = (-1)**i
    
print(points)
print()
print(labels)
X = points
y = labels

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1. -1.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1. -1.  0.  0.  0.  0.  0.  0.]
 [-1. -1. -1. -1.  1.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1. -1.  0.  0.  0.  0.]
 [-1. -1. -1. -1. -1. -1.  1.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1. -1.  0.  0.]
 [-1. -1. -1. -1. -1. -1. -1. -1.  1.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1. -1.]]

[ 1. -1.  1. -1.  1. -1.  1. -1.  1. -1.]


In [51]:
pna = Pnorm_accelerated(2)
# X, y= get_dataset(100)
M = X * y[:, np.newaxis]
final_w = pna.iterate(X, y)
accuracy = np.sum(M @ final_w > 0)/M.shape[0]
print(accuracy)




Acc: 0:   2%|▏         | 16/1000 [00:00<00:12, 80.84it/s]

0
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:   4%|▎         | 36/1000 [00:00<00:10, 90.02it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:   6%|▌         | 56/1000 [00:00<00:10, 91.39it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:   8%|▊         | 76/1000 [00:00<00:09, 92.86it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  10%|▉         | 96/1000 [00:01<00:09, 92.48it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  12%|█▏        | 116/1000 [00:01<00:09, 91.19it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  13%|█▎        | 126/1000 [00:01<00:09, 90.76it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  15%|█▍        | 146/1000 [00:01<00:09, 89.86it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  17%|█▋        | 166/1000 [00:01<00:08, 93.77it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  19%|█▊        | 186/1000 [00:02<00:08, 92.87it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  21%|██        | 206/1000 [00:02<00:09, 85.53it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  22%|██▏       | 224/1000 [00:02<00:09, 78.99it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  24%|██▍       | 242/1000 [00:02<00:09, 79.55it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  26%|██▌       | 260/1000 [00:02<00:09, 80.91it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  27%|██▋       | 270/1000 [00:03<00:08, 84.98it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  28%|██▊       | 279/1000 [00:03<00:13, 55.15it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  30%|██▉       | 295/1000 [00:03<00:11, 63.68it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  31%|███▏      | 313/1000 [00:03<00:09, 72.54it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  33%|███▎      | 332/1000 [00:04<00:08, 74.57it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  34%|███▍      | 340/1000 [00:04<00:09, 66.94it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  36%|███▌      | 355/1000 [00:04<00:11, 54.86it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  36%|███▌      | 362/1000 [00:04<00:11, 56.17it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  38%|███▊      | 375/1000 [00:05<00:14, 44.54it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  38%|███▊      | 380/1000 [00:05<00:13, 45.37it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  39%|███▉      | 392/1000 [00:05<00:14, 42.70it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  40%|███▉      | 398/1000 [00:05<00:16, 37.28it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  40%|████      | 405/1000 [00:05<00:13, 42.50it/s]

0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  41%|████▏     | 414/1000 [00:06<00:18, 31.08it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  42%|████▏     | 418/1000 [00:06<00:20, 28.98it/s]

0.9
0.9
0.9


Acc: 0:  43%|████▎     | 428/1000 [00:06<00:16, 34.17it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  43%|████▎     | 432/1000 [00:06<00:21, 26.40it/s]

0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  44%|████▎     | 436/1000 [00:07<00:24, 23.06it/s]

0.9
0.9
0.9
0.9


Acc: 0:  45%|████▍     | 448/1000 [00:07<00:15, 35.11it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  45%|████▌     | 453/1000 [00:07<00:15, 34.68it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  46%|████▌     | 457/1000 [00:07<00:19, 27.89it/s]

0.9
0.9
0.9


Acc: 0:  46%|████▌     | 461/1000 [00:08<00:25, 21.20it/s]

0.9
0.9


Acc: 0:  46%|████▋     | 464/1000 [00:08<00:28, 18.74it/s]

0.9
0.9
0.9


Acc: 0:  47%|████▋     | 470/1000 [00:08<00:27, 19.46it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  47%|████▋     | 473/1000 [00:08<00:26, 20.17it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  48%|████▊     | 482/1000 [00:09<00:22, 23.26it/s]

0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  49%|████▊     | 487/1000 [00:09<00:30, 16.81it/s]

0.9
0.9
0.9
0.9
0.9


Acc: 0:  49%|████▉     | 492/1000 [00:09<00:29, 17.51it/s]

0.9
0.9
0.9
0.9
0.9


Acc: 0:  50%|████▉     | 498/1000 [00:10<00:27, 18.47it/s]

0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  51%|█████     | 509/1000 [00:10<00:14, 32.87it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  51%|█████▏    | 514/1000 [00:10<00:13, 36.55it/s]

0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  52%|█████▏    | 522/1000 [00:10<00:18, 25.36it/s]

0.9
0.9
0.9
0.9
0.9


Acc: 0:  53%|█████▎    | 527/1000 [00:10<00:15, 29.89it/s]

0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  54%|█████▎    | 536/1000 [00:11<00:16, 28.91it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  55%|█████▍    | 545/1000 [00:11<00:14, 31.38it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  55%|█████▌    | 554/1000 [00:11<00:14, 30.65it/s]

0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  56%|█████▌    | 558/1000 [00:12<00:18, 23.64it/s]

0.9
0.9
0.9
0.9
0.9


Acc: 0:  56%|█████▋    | 563/1000 [00:12<00:15, 27.90it/s]

0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  57%|█████▋    | 570/1000 [00:12<00:17, 24.87it/s]

0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  58%|█████▊    | 581/1000 [00:12<00:11, 35.76it/s]

0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9


Acc: 0:  58%|█████▊    | 585/1000 [00:13<00:20, 20.27it/s]

0.9
0.9
0.9
0.9
0.9


Acc: 0:  59%|█████▉    | 589/1000 [00:13<00:23, 17.40it/s]

0.9
0.9


Acc: 0:  59%|█████▉    | 592/1000 [00:13<00:27, 14.76it/s]

0.9
0.9
0.9
0.9


Acc: 0:  60%|█████▉    | 595/1000 [00:14<00:32, 12.64it/s]

0.9
0.9


Acc: 0:  60%|█████▉    | 599/1000 [00:14<00:31, 12.81it/s]

0.9
0.9
0.9


Acc: 0:  60%|██████    | 601/1000 [00:14<00:33, 12.06it/s]

0.9
0.9
0.9


Acc: 0:  60%|██████    | 603/1000 [00:14<00:30, 13.09it/s]

0.9
0.9


Acc: 0:  61%|██████    | 607/1000 [00:15<00:30, 13.07it/s]

0.9
0.9
0.9


Acc: 0:  61%|██████    | 609/1000 [00:15<00:32, 11.87it/s]

0.9
0.9
0.9


Acc: 0:  61%|██████    | 611/1000 [00:15<00:34, 11.13it/s]

0.9
0.9


Acc: 0:  62%|██████▏   | 615/1000 [00:15<00:33, 11.43it/s]

0.9
0.9
0.9


Acc: 0:  62%|██████▏   | 617/1000 [00:16<00:35, 10.68it/s]

0.9
0.9


Acc: 0:  62%|██████▏   | 619/1000 [00:16<00:31, 11.96it/s]

0.9
0.9
0.9


Acc: 0:  62%|██████▏   | 621/1000 [00:16<00:34, 11.02it/s]

0.9
0.9


Acc: 0:  62%|██████▎   | 625/1000 [00:16<00:35, 10.58it/s]

0.9
0.9
0.9


Acc: 0:  63%|██████▎   | 627/1000 [00:17<00:36, 10.29it/s]

0.9
0.9


Acc: 0:  63%|██████▎   | 629/1000 [00:17<00:37,  9.92it/s]

0.9
0.9
0.9


Acc: 0:  63%|██████▎   | 631/1000 [00:17<00:32, 11.31it/s]

0.9
0.9


Acc: 0:  64%|██████▎   | 635/1000 [00:17<00:30, 11.92it/s]

0.9
0.9
0.9


Acc: 0:  64%|██████▎   | 637/1000 [00:17<00:27, 13.11it/s]

0.9
0.9
0.9


Acc: 0:  64%|██████▍   | 639/1000 [00:18<00:30, 11.76it/s]

0.9
0.9


Acc: 0:  64%|██████▍   | 641/1000 [00:18<00:33, 10.87it/s]

0.9
0.9


Acc: 0:  64%|██████▍   | 643/1000 [00:18<00:34, 10.43it/s]

0.9
0.9


Acc: 0:  65%|██████▍   | 647/1000 [00:18<00:30, 11.56it/s]

0.9
0.9
0.9


Acc: 0:  65%|██████▍   | 649/1000 [00:18<00:32, 10.79it/s]

0.9
0.9


Acc: 0:  65%|██████▌   | 651/1000 [00:19<00:29, 12.01it/s]

0.9
0.9
0.9


Acc: 0:  65%|██████▌   | 653/1000 [00:19<00:31, 11.12it/s]

0.9
0.9


Acc: 0:  66%|██████▌   | 657/1000 [00:19<00:32, 10.59it/s]

0.9
0.9
0.9


Acc: 0:  66%|██████▌   | 661/1000 [00:20<00:29, 11.58it/s]

0.9
0.9
0.9
0.9


Acc: 0:  66%|██████▋   | 663/1000 [00:20<00:26, 12.77it/s]

0.9
0.9
0.9


Acc: 0:  67%|██████▋   | 667/1000 [00:20<00:25, 12.93it/s]

0.9
0.9
0.9


Acc: 0:  67%|██████▋   | 669/1000 [00:20<00:28, 11.56it/s]

0.9
0.9


Acc: 0:  67%|██████▋   | 671/1000 [00:20<00:30, 10.63it/s]

0.9
0.9


Acc: 0:  67%|██████▋   | 673/1000 [00:21<00:32, 10.17it/s]

0.9
0.9


Acc: 0:  68%|██████▊   | 675/1000 [00:21<00:34,  9.47it/s]

0.9
0.9


Acc: 0:  68%|██████▊   | 677/1000 [00:21<00:34,  9.34it/s]

0.9
0.9


Acc: 0:  68%|██████▊   | 679/1000 [00:21<00:34,  9.31it/s]

0.9
0.9
0.9


Acc: 0:  68%|██████▊   | 683/1000 [00:22<00:28, 11.05it/s]

0.9
0.9
0.9


Acc: 0:  68%|██████▊   | 685/1000 [00:22<00:25, 12.14it/s]

0.9
0.9


Acc: 0:  69%|██████▊   | 687/1000 [00:22<00:24, 13.01it/s]

0.9
0.9
0.9


Acc: 0:  69%|██████▉   | 691/1000 [00:22<00:26, 11.49it/s]

0.9
0.9
0.9


Acc: 0:  69%|██████▉   | 693/1000 [00:22<00:28, 10.65it/s]

0.9
0.9


Acc: 0:  70%|██████▉   | 695/1000 [00:23<00:29, 10.23it/s]

0.9
0.9
0.9
0.9


Acc: 0:  70%|███████   | 700/1000 [00:23<00:21, 14.19it/s]

0.9
0.9
0.9


Acc: 0:  70%|███████   | 702/1000 [00:23<00:23, 12.49it/s]

0.9
0.9


Acc: 0:  70%|███████   | 704/1000 [00:23<00:25, 11.73it/s]

0.9
0.9
0.9


Acc: 0:  71%|███████   | 708/1000 [00:24<00:26, 10.85it/s]

0.9
0.9
0.9


Acc: 0:  71%|███████   | 712/1000 [00:24<00:22, 12.56it/s]

0.9
0.9
0.9
0.9


Acc: 0:  71%|███████▏  | 714/1000 [00:24<00:23, 12.11it/s]

0.9
0.9
0.9


Acc: 0:  72%|███████▏  | 718/1000 [00:25<00:24, 11.62it/s]

0.9
0.9
0.9
0.9


Acc: 0:  72%|███████▏  | 721/1000 [00:25<00:21, 13.13it/s]

0.9
0.9
0.9


Acc: 0:  72%|███████▎  | 725/1000 [00:25<00:19, 13.95it/s]

0.9
0.9
0.9
0.9


Acc: 0:  73%|███████▎  | 727/1000 [00:25<00:21, 12.75it/s]

0.9
0.9
0.9


Acc: 0:  73%|███████▎  | 732/1000 [00:26<00:21, 12.55it/s]

0.9
0.9
0.9


Acc: 0:  74%|███████▎  | 736/1000 [00:26<00:19, 13.27it/s]

0.9
0.9
0.9
0.9


Acc: 0:  74%|███████▍  | 740/1000 [00:26<00:18, 13.75it/s]

0.9
0.9
0.9
0.9


Acc: 0:  74%|███████▍  | 742/1000 [00:26<00:20, 12.66it/s]

0.9
0.9
0.9


Acc: 0:  75%|███████▍  | 746/1000 [00:27<00:21, 11.78it/s]

0.9
0.9
0.9


Acc: 0:  75%|███████▍  | 748/1000 [00:27<00:21, 11.66it/s]

0.9
0.9
0.9


Acc: 0:  75%|███████▌  | 752/1000 [00:27<00:21, 11.39it/s]

0.9
0.9
0.9


Acc: 0:  75%|███████▌  | 754/1000 [00:27<00:21, 11.31it/s]

0.9
0.9
0.9


Acc: 0:  76%|███████▌  | 758/1000 [00:28<00:21, 11.36it/s]

0.9
0.9
0.9


Acc: 0:  76%|███████▌  | 760/1000 [00:28<00:22, 10.68it/s]

0.9
0.9


Acc: 0:  76%|███████▋  | 764/1000 [00:28<00:19, 12.36it/s]

0.9
0.9
0.9
0.9


Acc: 0:  77%|███████▋  | 766/1000 [00:28<00:19, 11.93it/s]

0.9
0.9
0.9
0.9


Acc: 0:  77%|███████▋  | 771/1000 [00:29<00:18, 12.43it/s]

0.9
0.9
0.9


Acc: 0:  77%|███████▋  | 773/1000 [00:29<00:19, 11.62it/s]

0.9
0.9


Acc: 0:  78%|███████▊  | 775/1000 [00:29<00:18, 12.31it/s]

0.9
0.9
0.9


Acc: 0:  78%|███████▊  | 779/1000 [00:30<00:17, 12.71it/s]

0.9
0.9
0.9


Acc: 0:  78%|███████▊  | 781/1000 [00:30<00:18, 11.79it/s]

0.9
0.9
0.9


Acc: 0:  78%|███████▊  | 785/1000 [00:30<00:19, 11.22it/s]

0.9
0.9
0.9


Acc: 0:  78%|███████▊  | 785/1000 [00:30<00:08, 25.58it/s]


AttributeError: 'NoneType' object has no attribute 'reshape'

In [ ]:
num_examples = 100
# dim = 5
# X = np.random.rand(num_examples, dim)
# y = np.random.choice([-1, 1], (num_examples))
X, y= get_dataset(num_examples)
gentile = Gentile(3, .5, 1, 1)
final_weights = gentile.solve(X, y)
accuracy_metric = np.sum(y * (X @ final_weights) > 0)/X.shape[0]
print(y * X @ final_weights)
clf = Perceptron(tol=1e-3, random_state=0, fit_intercept=False)
clf.fit(X, y)
breakpoint()
accuracy_metric_scipy = y * np.squeeze(X @ clf.coef_.T)